# Generated by Django 4.1.3 on 2023-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(help_text='广告内容', null=True, verbose_name='广告内容'),
        ),
    ]
