# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='菜单名称', max_length=150, verbose_name='菜单名称')),
                ('icon', models.CharField(help_text='菜单图标', max_length=50, verbose_name='菜单图标')),
                ('url', models.CharField(help_text='菜单URL', max_length=255, verbose_name='菜单URL')),
                ('pid', models.IntegerField(default=0, help_text='上级ID', verbose_name='上级ID')),
                ('type', models.IntegerField(default=0, help_text='菜单类型：0-菜单 1-节点', verbose_name='菜单类型：0-菜单 1-节点')),
                ('permission', models.CharField(help_text='权限节点', max_length=150, verbose_name='权限节点')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='职级状态：1-正常 2-停用', verbose_name='职级状态：1-正常 2-停用')),
                ('target', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='打开方式：1-内部打开 2-外部打开', verbose_name='打开方式：1-内部打开 2-外部打开')),
                ('sort', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('note', models.CharField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'db_table': 'django_menu',
            },
        ),
    ]
