# Generated by Django 4.1.3 on 2023-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='菜单状态：1-正常 2-停用', verbose_name='菜单状态：1-正常 2-停用'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.IntegerField(choices=[(1, '内部打开'), (2, '外部打开')], default=1, help_text='打开方式：1-内部打开 2-外部打开', verbose_name='打开方式：1-内部打开 2-外部打开'),
        ),
    ]
